# Generated by Django 5.2.10 on 2026-05-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'tour_categories',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=1)),
                ('max_participants', models.IntegerField(default=10)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.country')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcategory')),
            ],
            options={
                'db_table': 'tours',
            },
        ),
    ]
