# Generated by Django 5.2.10 on 2026-05-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='main_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
